spring.application.name=web-crawling

logging.level.root=INFO
logging.file.name=scraper_dmx.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %level - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %level - %msg%n
logging.charset.console=UTF-8
logging.charset.file=UTF-8